### ISSUE TITLE
trie du data frame

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/OpenObs#11]
Le trie du data frame se fait sur les select input **pas sur les dates** à modifier

**Comment by VincentBlase** [comment]
Corrigé

**Comment by yannickkk** [comment]
ok mais fait un commit que je puisse vérifier.

**Comment by yannickkk** [comment]
et clore si c'est ok

**Comment by VincentBlase** [comment]
J'avais mal compris le commentaire. Cette fois c'est bon je l'ai ajouté et commit

**Comment by yannickkk** [comment]
ça marche je ferme
