### ISSUE TITLE
petit coup de main: calcul des centroïdes

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/OpenObs#12]
######a mettre dans global: on teste si les coordonnées existent dans le jeu de données (si elles n'existe pas aller cherche le geojson, si il n'existe pas afficher une erreur). Si oui on remplace les virgules par des points et on met au format numérique
if (length(grep("^geo_2_lat", names(dat))) != 0){
dat[,grep("^geo_2_lat", names(dat))]<-as.numeric(gsub(",", ".",dat[,grep("^geo_2_lat", names(dat))]))
dat[,grep("^geo_2_long", names(dat))]<-as.numeric(gsub(",", ".",dat[,grep("^geo_2_long", names(dat))]))
}
######a mettre ou il faut: calcul du centroïde des localisations de la variable de groupement geo_2~
cent<-aggregate(dat[,c(grep("^geo_2_lat", names(dat)), grep("^geo_2_long", names(dat)))], list(dat[,grep("^geo_2\\~", names(dat))]), mean)

**Comment by VincentBlase** [comment]
C'est rajouté ! Merci

**Comment by yannickkk** [comment]
le calcul semble correct ok
