### ISSUE TITLE
reprojection des geojson

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/OpenObs#13]
#########reprojection du geojson en wgs84
wgs84 <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
cent_dist_geo <- spTransform(cent_dist_geo,wgs84)

**Comment by VincentBlase** [comment]
Je ne comprends pas, a quoi cela sert ? Je crois qu'on en avait parlé mais je ne me rappelle plus très bien
